// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9i0ZdCcuD_wfYPaLjY4wJx2oAVffp6v4',
    appId: '1:335966779035:web:0b61351981243accd6383e',
    messagingSenderId: '335966779035',
    projectId: 'itssutras',
    authDomain: 'itssutras.firebaseapp.com',
    databaseURL: 'https://itssutras-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itssutras.appspot.com',
    measurementId: 'G-62LJ3JNHCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM20gY3JT9mnqFsJM3aeARHUQCWhIZ6As',
    appId: '1:335966779035:android:0dbb22e11e7cadb8d6383e',
    messagingSenderId: '335966779035',
    projectId: 'itssutras',
    databaseURL: 'https://itssutras-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itssutras.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_BESPFDCeNxlT4Fvi64EZUPFJDcLZQ94',
    appId: '1:335966779035:ios:a80d58c8782dda59d6383e',
    messagingSenderId: '335966779035',
    projectId: 'itssutras',
    databaseURL: 'https://itssutras-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itssutras.appspot.com',
    iosClientId: '335966779035-rqkvvrurht59bf5ip0r0dvl0q222p9gm.apps.googleusercontent.com',
    iosBundleId: 'com.rajeabhilash.sutra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_BESPFDCeNxlT4Fvi64EZUPFJDcLZQ94',
    appId: '1:335966779035:ios:a80d58c8782dda59d6383e',
    messagingSenderId: '335966779035',
    projectId: 'itssutras',
    databaseURL: 'https://itssutras-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itssutras.appspot.com',
    iosClientId: '335966779035-rqkvvrurht59bf5ip0r0dvl0q222p9gm.apps.googleusercontent.com',
    iosBundleId: 'com.rajeabhilash.sutra',
  );
}
